# Generated by Django 6.0.5 on 2026-05-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('product_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20)),
                ('cabinet_width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cabinet_height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pixel_pitch', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
