# Generated by Django 6.0.5 on 2026-05-18 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('wall_width_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wall_height_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('columns', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('m', 'Meters'), ('ft', 'Feet')], default='m', max_length=10)),
                ('resolution_preset', models.CharField(blank=True, max_length=20)),
                ('redundancy', models.CharField(choices=[('none', 'No redundancy'), ('power', 'Power'), ('data', 'Data')], default='none', max_length=20)),
                ('content_mode', models.CharField(choices=[('default_image', 'Default image'), ('preview_video', 'Preview video'), ('upload_image', 'Upload image'), ('no_image', 'No image')], default='default_image', max_length=40)),
                ('custom_image_path', models.CharField(blank=True, max_length=255)),
                ('calculated_width_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('calculated_height_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('calculated_area_m2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('calculated_resolution_width', models.PositiveIntegerField()),
                ('calculated_resolution_height', models.PositiveIntegerField()),
                ('calculated_total_pixels', models.PositiveBigIntegerField()),
                ('calculated_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_max_power_w', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_typical_power_w', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_max_heat_btu_h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_typical_heat_btu_h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('novastar', 'Novastar'), ('colorlight', 'Colorlight'), ('other', 'Other')], max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('product_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.CharField(blank=True, help_text='Frontend asset key/path, for example leds/indoor/immersifPro.png.', max_length=255)),
                ('thumbnail_image', models.CharField(blank=True, help_text='Frontend asset key/path, for example leds/indoor/immersifPro.png.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LED model family',
                'verbose_name_plural': 'LED model families',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=160)),
                ('pixel_pitch', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brightness_nits', models.PositiveIntegerField()),
                ('cabinet_width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cabinet_height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cabinet_depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cabinet_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('refresh_rate_hz', models.PositiveIntegerField()),
                ('web_price_per_cabinet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_width_px_per_cabinet', models.PositiveIntegerField()),
                ('resolution_height_px_per_cabinet', models.PositiveIntegerField()),
                ('max_power_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typical_power_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_heat_btu_h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typical_heat_btu_h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productfamily')),
            ],
            options={
                'verbose_name': 'LED variant',
                'verbose_name_plural': 'LED variants',
                'ordering': ['family__display_order', 'family__name', 'display_order', 'pixel_pitch'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_prices', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='configurationproject',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_projects', to='products.controller'),
        ),
        migrations.AddField(
            model_name='configurationproject',
            name='selected_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_projects', to='products.productvariant'),
        ),
    ]
